### PR TITLE
WIP: The all in email...

### LINKED ISSUE #10: Do All In Memo.

### PR DESCRIPTION
**Pull request by punkcoder**
includes the update for the all in email.

### CODE REVIEW

**Comment by punkcoder** [comment]
Will... I just realized courtesy of my wife that your message is missing.

**Comment by kernelmethod** [comment]
> Will... I just realized courtesy of my wife that your message is missing.

Oh lol, I think I missed that part of the last meeting. I'll shoot one off in a few minutes.

**Comment by punkcoder** [comment]
All good I won't get to it tonight... starting to shutdown now. Just make sure that you reply to the group not to Aaron... unlike me, Robbyn was scrambling looking for my message.

**Comment by kernelmethod** [comment]
btw I sent an email to that thread, if you could re-run your script and commit the changes I'll take a look and get this merged in.

**Comment by punkcoder** [comment]
@kernelmethod this one should be ready to go.

**Pull request merged**
